### ISSUE TITLE
Очистка репозитория

### ISSUE THREAD

**Issue by gluhow** [GosNIIAS/mfcieditor#1]
В репозитории должны находится только файлы **необходимые** для сборки. Всякие личные настройки и бекап не должны быть в нем. Для удобства все файлы которые генерятся автоматом, помещают в файл  .gitignore
Шаблон для него я выслал. Надо добавить его в репозиторий и удалить вручную те файлы которые уже были добавлены, но не нужны

**Comment by gluhow** [comment]
Не удалена папка backup

**Comment by NasShev** [comment]
Задача выполнена
